export const SEARCH="SEARCH";
export const SEARCH_TEXT="SEARCH_TEXT"; 
export const NEWS_SOURCE="NEWS_SOURCE";
export const NEWS_ERROR_RECEIVE="NEWS_ERROR_RECEIVE";
export const SEARCH_ITEMS="SEARCH_ITEMS";

